use AdventureWorks2022;

--1.1 Get total sales revenue (all time).
--Purpose: Calculates total number of sales orders and total revenue to measure overall company performance.
select count(SalesOrderID) as Total_Orders, Sum(TotalDue) as Total_Revenue
from sales.SalesOrderHeader

--1.2 Get sales revenue by year.
--Purpose: Compares total revenue across years to identify annual growth or decline trends.
Select year(OrderDate) as Year,sum(totaldue) as Total_Revenue
from Sales.SalesOrderHeader
group by YEAR(OrderDate)
order by Total_Revenue desc

--1.3 Get sales revenue by month in 2013.
--Purpose: Tracks monthly performance during 2013 to identify seasonal sales trends.
Select year(OrderDate) as Year,MONTH(OrderDate) as month,sum(totaldue) as Total_Revenue
from Sales.SalesOrderHeader
where year(OrderDate)=2013
group by YEAR(OrderDate),MONTH(OrderDate)
order by month 

--1.4 Get sales revenue by quarter (all years).
--Purpose: Evaluates quarterly sales performance across all years for trend analysis.
Select year(OrderDate) as Year,CONCAT('Q',DATEPART(QUARTER,OrderDate)) As Quarter_Num,sum(totaldue) as Total_Revenue
from Sales.SalesOrderHeader 
group by DATEPART(QUARTER,OrderDate),year(OrderDate)
order by Year,Quarter_Num asc

--1.5 Get top 2 years with highest revenue.
--Purpose: Identifies the best-performing years based on total revenue.
select top 2 YEAR(OrderDate)AS  SALES_YEAR,sum(TotalDue) AS Total_REVENUE
from Sales.SalesOrderHeader
GROUP BY YEAR(OrderDate)
ORDER BY Total_REVENUE DESC

--1.6 Get sales revenue,total orders by quarter for a specific year Range.
--Purpose: Analyzes quarterly sales and orders between 2011–2013 to monitor short-term performance.
Select year(OrderDate) As Sales_Year,count(SalesOrderID) Total_Orders,CONCAT('Q',DATEPART(QUARTER,OrderDate)) As Sales_Quarter,SUM(TotalDue) Total_Sales
from Sales.SalesOrderHeader
where YEAR(OrderDate) between 2011 and 2013
group by DATEPART(QUARTER,OrderDate),YEAR(OrderDate)
order by Total_Sales desc

--1.7 Get cumulative revenue over years.
--Purpose: Displays total revenue accumulated year by year to show growth progression.
WITH YearlySales AS (
    SELECT YEAR(OrderDate) AS SalesYear,
           SUM(TotalDue) AS TotalRevenue
    FROM Sales.SalesOrderHeader
    GROUP BY YEAR(OrderDate)
)
SELECT SalesYear,
       TotalRevenue,
       SUM(TotalRevenue) OVER (ORDER BY SalesYear) AS CumulativeRevenue
FROM YearlySales
ORDER BY SalesYear asc;

--1.8 Get average revenue per Year.
--Purpose: Calculates average order revenue per year to measure sales efficiency annually.
SELECT YEAR(OrderDate) AS Sales_Year , AVG(TotalDue) AS AvgRevenue
FROM Sales.SalesOrderHeader
group by YEAR(OrderDate)
order by AvgRevenue 

--1.9 Get revenue by region.
--Purpose: Compares total revenue generated by each sales region to assess geographic performance.
select st.Name, Sum(soh.TotalDue) as Total_Revenue
from sales.SalesOrderHeader soh
join Sales.SalesTerritory st
on soh.TerritoryID=st.TerritoryID
group by st.Name
order by Total_Revenue desc

--1.10 Get bottom/top 10 customers by revenue.
--Purpose: Identifies the least and most valuable customers based on total spending.
select top 10 c.CustomerID ,Sum(TotalDue) as Total_Sales 
from Sales.SalesOrderHeader soh
join Sales.Customer c
on soh.CustomerID=c.CustomerID
group by c.CustomerID
order by Total_Sales 

select top 10 c.CustomerID ,Sum(TotalDue) as Total_Sales 
from Sales.SalesOrderHeader soh
join Sales.Customer c
on soh.CustomerID=c.CustomerID
group by c.CustomerID
order by Total_Sales desc

--1.11 Get average revenue per Quarter for each year.
--Purpose: Shows average revenue within each quarter to evaluate consistency in quarterly performance.
Select year(OrderDate) as Year,CONCAT('Q',DATEPART(QUARTER,OrderDate)) As Quarter_Num,AVG(totaldue) as Avg_Revenue
from Sales.SalesOrderHeader 
group by DATEPART(QUARTER,OrderDate),year(OrderDate)
order by Year,Quarter_Num asc

--1.12 Get Total Orders per region.
--Purpose: Measures total number of orders per region to compare regional customer activity.
select st.Name, count(soh.SalesOrderID) as Total_orders
from sales.SalesOrderHeader soh
join Sales.SalesTerritory st
on soh.TerritoryID=st.TerritoryID
group by st.Name
order by Total_orders desc

--1.13 Get total revenue per product.
--Purpose: Calculates total sales revenue for each product to identify best sellers.
select p.ProductID,
       p.Name AS ProductName,
       SUM(sod.LineTotal) AS TotalRevenue
from Sales.SalesOrderDetail sod
join Production.Product p
     ON sod.ProductID = p.ProductID
GROUP BY p.ProductID, p.Name
ORDER BY TotalRevenue DESC;

--1.14 Get total revenue per productCategory/SubCategory.
--Purpose: Measures total sales per category and subcategory to identify top-performing product lines.
SELECT 
    pc.Name AS CategoryName,
    SUM(sod.LineTotal) AS TotalRevenue
FROM Sales.SalesOrderDetail sod
JOIN Production.Product p
    ON sod.ProductID = p.ProductID
JOIN Production.ProductSubcategory psc
    ON p.ProductSubcategoryID = psc.ProductSubcategoryID
JOIN Production.ProductCategory pc
    ON psc.ProductCategoryID = pc.ProductCategoryID
GROUP BY pc.Name
ORDER BY TotalRevenue DESC;

--1.15 Get Top 10 Products by Total Revenue.
--Purpose: Lists the top 10 products generating the highest total sales revenue.
SELECT TOP 10 p.ProductID,p.Name AS ProductName,SUM(sod.LineTotal) AS TotalRevenue
FROM Sales.SalesOrderDetail sod
JOIN Production.Product p
    ON sod.ProductID = p.ProductID
GROUP BY p.ProductID, p.Name
ORDER BY TotalRevenue DESC;
